FROM registry.redhat.io/ubi9/ubi:latest@sha256:12b3fafdd3d51cb894196ecf944b1119ff4bc2d390a3a57fd141c3b5f0de9b15 AS builder
WORKDIR /opt/app-root/src
USER root

RUN dnf install --nodocs -y golang git && \
    dnf clean all && \
    rm -rf /var/cache/yum

COPY .git .git
COPY tempo tempo
# this directory is checked by ecosystem-cert-preflight-checks task in Konflux
COPY tempo/LICENSE /licenses/
WORKDIR /opt/app-root/src/tempo

RUN exportOrFail() { echo $1; if [[ $1 == *= ]]; then echo "Error: empty variable assignment"; exit 1; else export "$1"; fi } && \
    exportOrFail GIT_BRANCH=`git rev-parse --abbrev-ref HEAD` && \
    exportOrFail GIT_REVISION=`git rev-parse --short HEAD` && \
    exportOrFail VERSION="2.10.8" && \
    CGO_ENABLED=0 GOFIPS140=certified go build -C ./cmd/tempo -tags no_openssl -mod vendor \
      -o "tempo" -trimpath -ldflags "-s -w -X main.Branch=${GIT_BRANCH} -X main.Revision=${GIT_REVISION} -X main.Version=${VERSION}"

FROM registry.redhat.io/ubi9/ubi-micro:latest@sha256:7a0454cbd9bd847e8f6a63b6f0254a6efbeb6e0ed71a5d824a4f6cccbe626650 AS ubi-micro-base
FROM registry.redhat.io/ubi9/ubi:latest@sha256:12b3fafdd3d51cb894196ecf944b1119ff4bc2d390a3a57fd141c3b5f0de9b15 AS image-builder
COPY --from=ubi-micro-base / /mnt/rootfs

RUN rpm --root /mnt/rootfs --import /etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release && \
    dnf install -y \
      --installroot /mnt/rootfs \
      --releasever 9 \
      --setopt install_weak_deps=false \
      --setopt reposdir=/etc/yum.repos.d \
      --nodocs \
      ca-certificates && \
    dnf clean all --installroot /mnt/rootfs && \
    rm -rf /mnt/rootfs/var/cache/*

FROM scratch
WORKDIR /
COPY --from=image-builder /mnt/rootfs/ /
COPY tempo/LICENSE /licenses/
COPY --from=builder /opt/app-root/src/tempo/cmd/tempo/tempo /usr/bin/tempo

ENV GODEBUG=fips140=auto
ARG USER_UID=1001
USER ${USER_UID}
ENTRYPOINT ["/usr/bin/tempo"]

ARG VERSION=0.22.0-2
LABEL release="${VERSION}" \
      version="${VERSION}" \
      vendor="Red Hat, Inc." \
      distribution-scope="public" \
      url="https://github.com/grafana/tempo-operator" \
      com.redhat.component="tempo-container" \
      cpe="cpe:/a:redhat:openshift_distributed_tracing:3.11::el9" \
      name="rhosdt/tempo-rhel9" \
      summary="Tempo server" \
      description="Container for Tempo application" \
      maintainer="Red Hat <support@redhat.com>" \
      io.k8s.description="Container for Tempo application." \
      io.openshift.expose-services="3100:http,4317:otlp-grpc,4318:otlp-http" \
      io.openshift.tags="tracing" \
      io.k8s.display-name="Tempo"
