FROM registry.redhat.io/ubi9/nodejs-22:latest@sha256:6d86fecb222cfc477376a582665e55741cf403240a83bee2b59331c77a4dce96 AS builder-ui
 
WORKDIR /opt/app-root/src
USER root

COPY patches patches
COPY jaeger-ui jaeger-ui
# this directory is checked by ecosystem-cert-preflight-checks task in Konflux
COPY jaeger-ui/LICENSE /licenses/
WORKDIR /opt/app-root/src/jaeger-ui

# add deprecation notice to Jaeger UI
RUN dnf install -y patch
RUN patch -p1 < /opt/app-root/src/patches/jaegerui_deprecation_notice.patch

RUN npm ci --ignore-scripts
RUN npm run build

FROM registry.redhat.io/ubi9/ubi:latest@sha256:206b65b8ee0f04b992818c9a51b29081b14974630d4850bc358097d0c44ea156 AS builder

WORKDIR /opt/app-root/src
USER root

RUN dnf install --nodocs -y golang git && \
    dnf clean all && \
    rm -rf /var/cache/yum

COPY .git .git
COPY jaeger jaeger
# this directory is checked by ecosystem-cert-preflight-checks task in Konflux
COPY jaeger/LICENSE /licenses/
WORKDIR /opt/app-root/src/jaeger

COPY --from=builder-ui /opt/app-root/src/jaeger-ui /opt/app-root/src/jaeger-ui

RUN rm -rf ./cmd/query/app/ui/actual && mkdir ./cmd/query/app/ui/actual && cp -r /opt/app-root/src/jaeger-ui/packages/jaeger-ui/build/* ./cmd/query/app/ui/actual/ && find ./cmd/query/app/ui/actual -type f | xargs gzip

RUN go version && \
    exportOrFail() { echo $1; if [[ $1 == *= ]]; then echo "Error: empty variable assignment"; exit 1; else export "$1"; fi } && \
    exportOrFail VERSION_PKG="github.com/jaegertracing/jaeger/internal/version" && \
    exportOrFail VERSION_DATE=`date -u +'%Y-%m-%dT%H:%M:%SZ'` && \
    exportOrFail GIT_LATEST_TAG="1.68.0" && \
    exportOrFail GIT_COMMIT_SHA=`git rev-parse HEAD` && \
    CGO_ENABLED=0 GOFIPS140=certified go build -C ./cmd/query -mod=mod -tags no_openssl,ui \
      -o ./jaeger -trimpath -ldflags "-s -w \
                -X ${VERSION_PKG}.commitSHA=${GIT_COMMIT_SHA} \
                -X ${VERSION_PKG}.latestVersion=${GIT_LATEST_TAG} \
                -X ${VERSION_PKG}.date=${VERSION_DATE}"

FROM registry.redhat.io/ubi9/ubi-micro:latest@sha256:f332c99eb8f798a8486821c91937f10ad64ee83d7e739303be2df051040918f6
ARG VERSION=0.22.0-1

RUN mkdir /licenses
COPY jaeger/LICENSE /licenses/.
COPY --from=builder /opt/app-root/src/jaeger/cmd/query/jaeger /usr/bin/jaeger

ENV GODEBUG=fips140=auto
ARG USER_UID=1001
USER ${USER_UID}
ENTRYPOINT ["/usr/bin/jaeger"]

LABEL release="${VERSION}" \
      version="${VERSION}" \
      vendor="Red Hat, Inc." \
      distribution-scope="public" \
      url="https://github.com/grafana/tempo-operator" \
      com.redhat.component="jaeger-query-container" \
      name="rhosdt/tempo-jaeger-query-rhel9" \
      summary="Jaeger Query" \
      description="This container provides Jaeger UI for Tempo" \
      maintainer="Red Hat <support@redhat.com>" \
      cpe="cpe:/a:redhat:openshift_distributed_tracing:3.11::el9" \
      io.k8s.description="This container provides Jaeger UI for Tempo." \
      io.openshift.expose-services="16686:uihttp" \
      io.openshift.tags="tracing" \
      io.k8s.display-name="Jaeger Query"
