FROM registry.redhat.io/ubi9/ubi:latest@sha256:206b65b8ee0f04b992818c9a51b29081b14974630d4850bc358097d0c44ea156 AS builder
WORKDIR /opt/app-root/src
USER root

RUN dnf install --nodocs -y golang git && \
    dnf clean all && \
    rm -rf /var/cache/yum

COPY .git .git
COPY tempo tempo
# this directory is checked by ecosystem-cert-preflight-checks task in Konflux
COPY tempo/LICENSE /licenses/
WORKDIR /opt/app-root/src/tempo

RUN exportOrFail() { echo $1; if [[ $1 == *= ]]; then echo "Error: empty variable assignment"; exit 1; else export "$1"; fi } && \
    exportOrFail GIT_BRANCH=`git rev-parse --abbrev-ref HEAD` && \
    exportOrFail GIT_REVISION=`git rev-parse --short HEAD` && \
    exportOrFail VERSION="2.10.8" && \
    CGO_ENABLED=0 GOFIPS140=certified go build -C ./cmd/tempo-query -tags no_openssl -mod vendor \
      -o "tempo-query" -trimpath -ldflags "-s -w -X main.Branch=${GIT_BRANCH} -X main.Revision=${GIT_REVISION} -X main.Version=${VERSION}"

FROM registry.redhat.io/ubi9/ubi-micro:latest@sha256:f332c99eb8f798a8486821c91937f10ad64ee83d7e739303be2df051040918f6 AS ubi-micro-base
FROM registry.redhat.io/ubi9/ubi:latest@sha256:206b65b8ee0f04b992818c9a51b29081b14974630d4850bc358097d0c44ea156 AS image-builder
COPY --from=ubi-micro-base / /mnt/rootfs

RUN rpm --root /mnt/rootfs --import /etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release && \
    dnf install -y \
      --installroot /mnt/rootfs \
      --releasever 9 \
      --setopt install_weak_deps=false \
      --setopt reposdir=/etc/yum.repos.d \
      --nodocs \
      ca-certificates && \
    dnf clean all --installroot /mnt/rootfs && \
    rm -rf /mnt/rootfs/var/cache/*

FROM scratch
WORKDIR /
COPY --from=image-builder /mnt/rootfs/ /
COPY tempo/LICENSE /licenses/
COPY --from=builder /opt/app-root/src/tempo/cmd/tempo-query/tempo-query /usr/bin/tempo-query

ENV GODEBUG=fips140=auto
ARG USER_UID=1001
USER ${USER_UID}
ENTRYPOINT ["/usr/bin/tempo-query"]

ARG VERSION=0.22.0-2
LABEL release="${VERSION}" \
      version="${VERSION}" \
      vendor="Red Hat, Inc." \
      distribution-scope="public" \
      url="https://github.com/grafana/tempo-operator" \
      com.redhat.component="tempo-query-container" \
      name="rhosdt/tempo-query-rhel9" \
      summary="Tempo Query" \
      description="This container exposes a Jaeger Query compatible API from Tempo" \
      maintainer="Red Hat <support@redhat.com>" \
      io.k8s.description="This container exposes a Jaeger Query compatible API from Tempo." \
      io.openshift.expose-services="16686:http,16687:metrics" \
      io.openshift.tags="tracing" \
      io.k8s.display-name="Tempo Query" \
      cpe="cpe:/a:redhat:openshift_distributed_tracing:3.11::el9"
