apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/pavolloffay/konflux-tempo?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch == "main" &&
      (".tekton/multi-arch-build-pipeline.yaml".pathChanged() ||
      ".tekton/tempo-tempo-pull-request.yaml".pathChanged() ||
      ".tekton/tempo-tempo-push.yaml".pathChanged() ||
      "Dockerfile.tempo".pathChanged() ||
      "tempo".pathChanged())
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: tempo
    appstudio.openshift.io/component: tempo-tempo
    pipelines.appstudio.openshift.io/type: build
  name: tempo-tempo-on-pull-request
  namespace: rhosdt-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/rhosdt-tenant/tempo/tempo-tempo:on-pr-{{revision}}
  - name: image-expires-after
    value: 5d
  - name: dockerfile
    value: Dockerfile.tempo
  - name: path-context
    value: .
  - name: build-platforms
    value:
      - localhost
      - linux/arm64
  #     - linux/ppc64le
  #     - linux/s390x
  pipelineRef:
    name: build-pipeline
  taskRunTemplate: {}
  workspaces:
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'