apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/os-observability/konflux-tempo?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    build.appstudio.openshift.io/build-nudge-files: "bundle-patch/update_bundle.sh"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch == "main" &&
      (".tekton/multi-arch-build-pipeline.yaml".pathChanged() ||
      ".tekton/tempo-opa-pull-request.yaml".pathChanged() ||
      ".tekton/tempo-opa-push.yaml".pathChanged() ||
      "Dockerfile.opa".pathChanged() ||
      "opa-openshift".pathChanged())
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: tempo
    appstudio.openshift.io/component: tempo-opa
    pipelines.appstudio.openshift.io/type: build
  name: tempo-opa-on-push
  namespace: rhosdt-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/rhosdt-tenant/tempo/tempo-opa:{{revision}}
  - name: dockerfile
    value: Dockerfile.opa
  - name: path-context
    value: .
  - name: build-platforms
    value:
      - localhost
      - linux/arm64
      - linux/ppc64le
      - linux/s390x
  pipelineRef:
    name: build-pipeline
  taskRunTemplate: {}
  workspaces:
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
